### ISSUE TITLE
Problens to install

### ISSUE THREAD

**Issue by ghost** [henesissrl/pyerg#2]
Hello.

I'm with some problens to install that.

"
erg/erg.cpp:51:14: error: '(anonymous union at erg/erg.cpp:51:14)' cannot be
      defined in a type specifier
    return ((union{ uint32_t i; char c[4];}){0x01020304}).c[0] == 1;
             ^
erg/erg.cpp:51:58: error: member reference base type 'void' is not a structure
      or union
    return ((union{ uint32_t i; char c[4];}){0x01020304}).c[0] == 1;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
erg/erg.cpp:49:23: error: no return statement in constexpr function
static constexpr bool isBigEndian()
                      ^
3 errors generated.
"

Can you help me?
Thanks.

**Comment by allebacco** [comment]
The simplest solution is to to modify the function:
```
static constexpr bool isBigEndian()
{
    return false;
}
```
because all the x86 are little endian and the ARM architecture are almost always used in little endian mode.

After this fix, you should able to install pyerg.

I will try to get the time to fix the issue in the next days.

**Comment by ghost** [comment]
Thank you!
